@OrderApi_HostAddress = http://localhost:5260
@Order = 8

### Get order
GET {{OrderApi_HostAddress}}/api/orders/{{Order}}
Accept: application/json

###

GET {{OrderApi_HostAddress}}/api/orders
Accept: application/json

###

### Create order
POST {{OrderApi_HostAddress}}/api/orders
Content-Type: application/json

{
  "orderNumber": "ORD-1001",
  "firstName": "Jane",
  "lastName": "Bruno",
  "status": "Placed",
  "totalCost": 19
}

###