@OrderApi_HostAddress = http://localhost:8080
@Order =1 

### Get order
GET {{OrderApi_HostAddress}}/api/orders/{{Order}}
Accept: application/json

###

GET {{OrderApi_HostAddress}}/api/orders
Accept: application/json

###

### Create order
POST {{OrderApi_HostAddress}}/api/orders
Content-Type: application/json

{
  "orderNumber": "ORD-1001",
  "firstName": "SCroge",
  "lastName": "McDiggy",
  "status": "Done",
  "totalCost": 19
}

###